version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: myapp-backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: myapp-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
